highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Faluke Aikebiaer's Resume
name: Faluke Aikebaier
email: faluke.aikebaier@gmail.com
email_full: faluke.aikebaier@gmail.com
website: github.io/Faluke-Aikebaier
website_full: https://jekyller.github.io/Faluke-Aikebaier
#github: trending
#twitter: twitter
tel: +358 417031671
tel_full: tel:+358 417031671
#google_maps: 'https://www.google.co.uk/maps/place/44+Perth+St,+Edinburgh,+Edinburgh+City+EH3+5BL'
address:
  street: Rikhard Nymanin tie 3 A 11
  postcode: 00370
  city: Helsinki
  country: Finland
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-slate